logging:
  level: "info"
  development: false
  encoding: "json"
  outputPaths:
    - "stdout"
  errorOutputPaths:
    - "stderr"
  encoderConfig:
    messageKey: "message"
    levelKey: "level"
    timeKey: "time"
    nameKey: "logger"
    callerKey: "caller"
    stacktraceKey: "stacktrace"
    lineEnding: ""
    levelEncoder: "lowercase"
    timeEncoder: "millis"
    durationEncoder: "string"
    callerEncoder: "short"
