logging:
  level: "info"
  development: false
  encoding: "json"
  disableStacktrace: false
  initialFields:
    app: coffee-shop
  outputPaths:
    - "stdout"
  errorOutputPaths:
    - "stderr"
  encoderConfig:
    messageKey: "message"
    levelKey: "level"
    timeKey: "timestamp"
    nameKey: "logger"
    callerKey: "caller"
    stacktraceKey: "stacktrace"
    lineEnding: ""
    levelEncoder: "lowercase"
    timeEncoder: "rfc3339"
    durationEncoder: "ms"
    callerEncoder: "short"
