logging:
  level: "debug"
  development: true # Use development mode (human-readable logs)
  encoding: "console"
  disableStacktrace: false
  initialFields:
    app: coffee-shop
  outputPaths:
    - "stdout"
  errorOutputPaths:
    - "stderr"
  encoderConfig:
    messageKey: "message"
    levelKey: "level"
    timeKey: "time"
    nameKey: "logger"
    callerKey: "caller"
    stacktraceKey: "stacktrace"
    lineEnding: ""
    levelEncoder: "capitalColor"
    timeEncoder: "rfc3339"
    durationEncoder: "string"
    callerEncoder: "short"
